behaviors:
  PandemicAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048  
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512     
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        encoding_size: 256
        learning_rate: 0.0003
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 20000000
    time_horizon: 128
    summary_freq: 10000
    threaded: true

environment_parameters: 
  infectedCount: 
    sampler_type: uniform
    sampler_parameters:
        min_value: 1
        max_value: 20