behaviors:
  PandemicAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512    
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 128
    summary_freq: 10000
    threaded: true
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 2000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0

environment_parameters: 
  infectedCount: 
    curriculum: 
      - 
        completion_criteria: 
          behavior: PandemicAgent
          measure: reward
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 8
        name: Lesson0
        value: 3
      - 
        completion_criteria: 
          behavior: PandemicAgent
          measure: reward
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 8
        name: Lesson1
        value: 5
      - 
        completion_criteria: 
          behavior: PandemicAgent
          measure: reward
          min_lesson_length: 1000
          signal_smoothing: true
          threshold: 8
        name: Lesson2
        value: 8
      - 
        completion_criteria: 
          behavior: PandemicAgent
          measure: reward
          min_lesson_length: 1000
          signal_smoothing: true
          threshold: 8
        name: Lesson3
        value: 12
      - 
        completion_criteria: 
          behavior: PandemicAgent
          measure: reward
          min_lesson_length: 1000
          signal_smoothing: true
          threshold: 8  
        name: Lesson4
        value: 20