behaviors:
  PandemicAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256     
      num_layers: 2
      vis_encode_type: simple
      memory:
        sequence_length: 64
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 128
    summary_freq: 10000
    threaded: true

environment_parameters: 
  infectedCount: 
    curriculum: 
      - 
        completion_criteria: 
          behavior: PandemicAgent
          measure: reward
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 5
        name: Lesson0
        value: 1
      - 
        completion_criteria: 
          behavior: PandemicAgent
          measure: reward
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 5
        name: Lesson1
        value: 2
      - 
        completion_criteria: 
          behavior: PandemicAgent
          measure: reward
          min_lesson_length: 1000
          signal_smoothing: true
          threshold: 5
        name: Lesson2
        value: 3
      - 
        completion_criteria: 
          behavior: PandemicAgent
          measure: reward
          min_lesson_length: 1000
          signal_smoothing: true
          threshold: 6
        name: Lesson3
        value: 5
      - 
        completion_criteria: 
          behavior: PandemicAgent
          measure: reward
          min_lesson_length: 1000
          signal_smoothing: true
          threshold: 8  
        name: Lesson4
        value: 10