behaviors:
  PandemicAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512     
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      gail:
        gamma: 0.99
        strength: 0.1
        encoding_size: 128
        learning_rate: 0.0003
        use_actions: false
        use_vail: false
        demo_path: ../../../Project/Assets/PandemicSimulation/Demo/singlehouse.demo
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        encoding_size: 256
        learning_rate: 0.0003
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 20000000
    time_horizon: 128
    summary_freq: 10000
    threaded: true

environment_parameters: 
  infectedCount: 
    curriculum: 
      - 
        completion_criteria: 
          behavior: PandemicAgent
          measure: reward
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 6
        name: Lesson0
        value: 0
      - 
        completion_criteria: 
          behavior: PandemicAgent
          measure: reward
          min_lesson_length: 100
          signal_smoothing: true
          threshold: 6
        name: Lesson1
        value: 5
      - 
        completion_criteria: 
          behavior: PandemicAgent
          measure: reward
          min_lesson_length: 1000
          signal_smoothing: true
          threshold: 6
        name: Lesson2
        value: 10
      - 
        completion_criteria: 
          behavior: PandemicAgent
          measure: reward
          min_lesson_length: 1000
          signal_smoothing: true
          threshold: 6
        name: Lesson3
        value: 15
      - 
        completion_criteria: 
          behavior: PandemicAgent
          measure: reward
          min_lesson_length: 1000
          signal_smoothing: true
          threshold: 8  
        name: Lesson4
        value: 20
      - 
        completion_criteria: 
          behavior: PandemicAgent
          measure: reward
          min_lesson_length: 1000
          signal_smoothing: true
          threshold: 8  
        name: Lesson5
        value: 25